import type { PortfolioData, SiteContent } from './types';

const marqueeSkills = [
  'React Native',
  'NestJS',
  'PostgreSQL',
  'GraphQL',
  'Stripe',
  'Docker',
  'TypeScript',
  'Redux-Saga',
  'Firebase',
  'Microservices',
];

/** Hero fields only — useful for admin defaults and tests. */
export const siteContentDefaults: SiteContent = {
  roleTagline: 'Lead Software Engineer',
  firstName: 'Imran',
  lastName: 'Khan',
  bio: '',
  location: '',
  experienceMeta: '7+ years',
  experienceFocus: 'Mobile & Backend',
};

export const defaultPortfolioData: PortfolioData = {
  version: 1,
  seo: {
    title: 'Imran Khan — Lead Engineer | Mobile & Backend Specialist',
    description:
      'Lead Software Engineer with 7+ years building high-performance React Native apps and scalable NestJS backends. Available for remote roles globally.',
    keywords: [
      'Imran Khan',
      'Lead Engineer',
      'React Native Developer',
      'NestJS',
      'Mobile Engineer',
      'Dhaka Bangladesh',
      'Portfolio',
    ],
  },
  site: {
    ...siteContentDefaults,
    bio: 'I build production-grade mobile apps and the resilient backends behind them. React Native on the front; NestJS, PostgreSQL and GraphQL on the back. Currently leading engineering at Jumatechs.',
    location: 'Dhaka, Bangladesh — available globally (remote)',
  },
  hero: {
    portfolioLine: 'Portfolio / 2026',
    marqueeSkills,
    ctaPrimaryLabel: 'Explore work',
    ctaPrimaryHref: '#projects',
    ctaSecondaryLabel: 'Get in touch',
    ctaSecondaryHref: '#contact',
  },
  navigation: {
    brandMonogram: 'IK',
    brandName: 'imran khan',
    availabilityLabel: 'Available',
    timezoneCity: 'Dhaka',
    timeZone: 'Asia/Dhaka',
    navItems: [
      { label: 'About', href: '#about', num: '01' },
      { label: 'Work', href: '#experience', num: '02' },
      { label: 'Projects', href: '#projects', num: '03' },
      { label: 'Stack', href: '#skills', num: '04' },
      { label: 'Contact', href: '#contact', num: '05' },
    ],
  },
  about: {
    sectionNum: '01',
    sectionLabel: 'About',
    manifestoKicker: 'Manifesto',
    manifestoBody:
      "An engineer's work is half code, half judgement. I care about the judgement.",
    headlineLine1Before: 'I ship things that ',
    headlineLine1Highlight: 'work',
    headlineLine2: 'Under load, on flaky networks,',
    headlineLine3Italic: 'at 2am for a release.',
    bodyParagraphs: [
      "I've spent the last seven years leading mobile and backend work across fintech, real estate, HR platforms and consumer apps. Currently Lead Engineer at Jumatechs, where I drive architecture across React Native and NestJS stacks, run CI/CD with GitHub Actions and Expo EAS, and mentor a small team of engineers.",
      'Before that I led hybrid mobile development at Intellier, shipped cross-platform products at Brain Station 23, and built public-facing products like the Bangladesh RAB CMS. I lean on AI tools (Copilot, Cursor) the way a chef uses a sharp knife — to move faster without cutting corners.',
    ],
    stats: [
      { n: '7+', label: 'Years building' },
      { n: '20+', label: 'Apps shipped' },
      { n: '3', label: 'Senior roles' },
      { n: '∞', label: 'Cups of tea' },
    ],
  },
  experience: {
    sectionNum: '02',
    sectionLabel: 'Selected Work History',
    titleLead: 'A decade of ',
    titleEmphasis: 'shipping things',
    titleTail: ' across mobile, backend and the messy bits in between.',
    roles: [
      {
        company: 'Jumatechs',
        title: 'Lead Engineer',
        period: '2025 — Present',
        years: '2025',
        bullets: [
          'Lead a cross-functional team driving architecture and code quality across mobile and backend systems.',
          'Architect React Native apps backed by NestJS, PostgreSQL and Supabase.',
          'Built CI/CD pipelines with GitHub Actions and Expo EAS — cut deployment time significantly.',
          'Shipped secure auth, real-time sync and Stripe payments to production.',
          'Integrated AI-assisted tooling (Copilot, Cursor) into team workflow; mentor juniors on API design, state management and testing.',
        ],
        tech: [
          'React Native',
          'NestJS',
          'PostgreSQL',
          'Supabase',
          'Expo EAS',
          'Stripe',
        ],
      },
      {
        company: 'Intellier',
        title: 'Senior Software Engineer',
        period: 'Jan 2023 — Jul 2025',
        years: '2023–25',
        bullets: [
          'Led hybrid mobile development using React Native, NestJS and Django.',
          'Architected JWT auth with row-level security policies for data integrity.',
          'Integrated Stripe payments and Google Maps SDK for location-aware features.',
          'Managed CI/CD lifecycle with GitHub Actions and Vercel.',
          'Guided technical decision-making and mentored juniors across concurrent projects.',
        ],
        tech: [
          'React Native',
          'NestJS',
          'Django',
          'Stripe',
          'Google Maps',
          'Vercel',
        ],
      },
      {
        company: 'Brain Station 23',
        title: 'Software Engineer',
        period: 'Jan 2020 — Dec 2023',
        years: '2020–23',
        bullets: [
          'Designed and shipped cross-platform applications using React Native and MSSQL.',
          'Built scalable backend services with payment and real-time features.',
          'Collaborated in agile teams to meet deadlines while keeping a high quality bar.',
        ],
        tech: ['React Native', 'MSSQL', 'Redux', 'Agile'],
      },
    ],
  },
  projects: {
    sectionNum: '03',
    sectionLabel: 'Selected Projects',
    titleLead: "Things I've ",
    titleEmphasis: 'built',
    titleMid:
      ' recently. Some live in app stores, some in government, ',
    titleTailItalic: 'some in the RMG factory floor.',
    aside:
      'A selection of work across mobile, backend and the integrations that hold them together. Links go to production where available.',
    moreSectionTitleBefore: 'More',
    moreSectionTitleEmphasis: ' work.',
    featured: [
      {
        name: 'Balanzify',
        tagline: 'HR & Payroll Microservice',
        description:
          'A full HR and payroll platform built as a set of NestJS microservices — onboarding, payslips, attendance, tax logic and leave management, all speaking GraphQL. Designed for enterprise scale.',
        period: 'Jul 2025 — Ongoing',
        category: 'Enterprise SaaS',
        tech: ['NestJS', 'PostgreSQL', 'GraphQL', 'Microservices'],
        links: [{ label: 'Live site', url: 'https://balanzify.com' }],
        accent: 'from-amber-glow/30 to-transparent',
        number: '01',
      },
      {
        name: 'BAZZILE',
        tagline: 'Real Estate Marketplace',
        description:
          'List, browse, buy and sell properties with Tinder-style swipe animations, location-based matching via Google Maps and real-time sync through Firebase. iOS on the App Store.',
        period: 'Jan 2025 — Jul 2025',
        category: 'Consumer Mobile',
        tech: [
          'React Native',
          'Firebase',
          'Redux-Saga',
          'Reanimated',
          'NestJS',
        ],
        links: [
          {
            label: 'App Store',
            url: 'https://apps.apple.com/us/app/bazzile/id1622224603',
          },
        ],
        accent: 'from-signal-green/20 to-transparent',
        number: '02',
      },
      {
        name: 'Bangladesh RAB',
        tagline: 'Government CMS',
        description:
          'Led backend architecture for the Bangladesh Rapid Action Battalion content management system. Scalable microservices in TypeScript and NestJS, robust APIs, Next.js frontend — deployed at rab.gov.bd.',
        period: 'Jan 2024 — Dec 2024',
        category: 'Government',
        tech: ['NestJS', 'TypeScript', 'PostgreSQL', 'Docker', 'Next.js'],
        links: [{ label: 'Visit rab.gov.bd', url: 'https://rab.gov.bd' }],
        accent: 'from-amber-glow/20 to-transparent',
        number: '03',
      },
      {
        name: 'MyRef',
        tagline: 'Field Rep Companion',
        description:
          'Customer support, task tracking and real-time rep communication. In-app chat, push notifications and WatermelonDB-powered offline sync for reliability on flaky networks.',
        period: 'Jan 2025 — Sep 2025',
        category: 'B2B Mobile',
        tech: ['React Native', 'WatermelonDB', 'NestJS', 'GraphQL', 'Sentry'],
        links: [
          {
            label: 'Play Store',
            url: 'https://play.google.com/store/apps/details?id=com.myref.app',
          },
        ],
        accent: 'from-bone/10 to-transparent',
        number: '04',
      },
      {
        name: 'Playzone',
        tagline: 'Real-time multiplayer. Classic games. Zero friction.',
        description:
          'A real-time multiplayer gaming platform where users play classic childhood games with friends — no signups, no lag, just instant play. Built on a microservices architecture with NestJS handling game logic and matchmaking, PostgreSQL for persistence, and Socket.IO powering sub-second real-time state sync between players. The Next.js frontend delivers a mobile-first, ad-free experience, and the entire system is containerized with Docker for consistent deployment across environments.',
        period: '2024 — Present',
        category: 'Full-Stack · Real-Time Web App',
        tech: [
          'Next.js',
          'TypeScript',
          'NestJS',
          'Socket.IO',
          'PostgreSQL',
          'Docker',
          'Microservices',
          'Tailwind CSS',
        ],
        links: [{ label: 'Live demo', url: 'https://playzone-update.vercel.app/' }],
        accent: 'from-amber-glow/30 to-transparent',
        number: '05',
      },
    ],
    more: [
      {
        name: 'GodConnect Online',
        tagline: 'Community app with live broadcasts',
        description:
          'Groups, live broadcasts, messaging, media uploads and a GPS-based church finder. Shipped to both stores.',
        period: '2023 — 2024',
        category: 'Social',
        tech: ['React Native', 'Redux-Saga', 'WatermelonDB', 'Firebase'],
        links: [
          {
            label: 'iOS',
            url: 'https://apps.apple.com/us/app/godconnect-online/id1518393186',
          },
          {
            label: 'Android',
            url: 'https://play.google.com/store/apps/details?id=com.godconnect.online',
          },
        ],
        accent: '',
        number: '06',
      },
      {
        name: 'IQApp Test',
        tagline: 'Personalized dashboards',
        description:
          'Dashboards, real-time notifications, GraphQL-optimized fetching and Stripe in-app payments over a Django API.',
        period: 'Sep — Dec 2025',
        category: 'Consumer',
        tech: ['React Native', 'GraphQL', 'Stripe', 'Django'],
        links: [],
        accent: '',
        number: '07',
      },
      {
        name: 'NIdle Finishing',
        tagline: 'RMG sector digitalization',
        description:
          'Digitalized the finishing process for the ready-made garments sector — React Native with GraphQL and NestJS.',
        period: 'Nov 2023 — Feb 2024',
        category: 'Industrial',
        tech: ['React Native', 'GraphQL', 'NestJS'],
        links: [{ label: 'Case study', url: 'https://intellier.com/nidle/' }],
        accent: '',
        number: '08',
      },
      {
        name: 'Team Pharma',
        tagline: 'Cross-platform pharma app',
        description:
          'NestJS microservices, PostgreSQL and Firebase push notifications serving pharmaceutical field teams.',
        period: 'Jul — Oct 2024',
        category: 'Healthtech',
        tech: ['React Native', 'NestJS', 'PostgreSQL', 'Firebase'],
        links: [{ label: 'Live site', url: 'https://teampharmabd.com/' }],
        accent: '',
        number: '09',
      },
      {
        name: 'JTI Sheikh App',
        tagline: 'AR filters on mobile',
        description:
          'Integrated Deep AR for real-time augmented reality filters on a React Native app. Redux-Saga for state.',
        period: 'Sep — Dec 2021',
        category: 'AR / Consumer',
        tech: ['React Native', 'Deep AR', 'Redux-Saga'],
        links: [],
        accent: '',
        number: '10',
      },
      {
        name: 'Converter & Wallet',
        tagline: 'Currency converter with history',
        description:
          'Lightweight currency-conversion and wallet app with a local database for conversion history.',
        period: '2020 — 2021',
        category: 'Utility',
        tech: ['React Native', 'Redux'],
        links: [
          {
            label: 'Play Store',
            url: 'https://play.google.com/store/apps/details?id=com.converter.wallet',
          },
        ],
        accent: '',
        number: '11',
      },
    ],
  },
  skills: {
    sectionNum: '04',
    sectionLabel: 'Toolbox',
    titleLead: 'The ',
    titleEmphasis: 'tools',
    titleTail: ' I reach for — grouped by where they live in the stack.',
    legendPrimary: 'Primary — daily',
    legendStrong: 'Strong — production',
    legendWorking: 'Working — shipped with',
    groups: [
      {
        label: 'A',
        heading: 'Mobile',
        items: [
          { name: 'React Native', level: 'Primary' },
          { name: 'Expo EAS', level: 'Primary' },
          { name: 'Redux / Redux-Saga', level: 'Primary' },
          { name: 'React Reanimated', level: 'Strong' },
          { name: 'WatermelonDB', level: 'Strong' },
          { name: 'iOS / App Store', level: 'Strong' },
          { name: 'Android / Play Store', level: 'Strong' },
          { name: 'Push Notifications', level: 'Strong' },
        ],
      },
      {
        label: 'B',
        heading: 'Backend',
        items: [
          { name: 'NestJS', level: 'Primary' },
          { name: 'TypeScript', level: 'Primary' },
          { name: 'GraphQL', level: 'Primary' },
          { name: 'PostgreSQL', level: 'Primary' },
          { name: 'Django', level: 'Strong' },
          { name: 'Supabase', level: 'Strong' },
          { name: 'Firebase', level: 'Strong' },
          { name: 'Microservices', level: 'Strong' },
          { name: 'JWT Auth / RLS', level: 'Strong' },
          { name: 'MSSQL', level: 'Working' },
        ],
      },
      {
        label: 'C',
        heading: 'Infra & DevEx',
        items: [
          { name: 'Docker', level: 'Strong' },
          { name: 'GitHub Actions', level: 'Primary' },
          { name: 'Vercel', level: 'Strong' },
          { name: 'Sentry', level: 'Strong' },
          { name: 'Unit Testing', level: 'Strong' },
          { name: 'Husky / pre-commit', level: 'Working' },
        ],
      },
      {
        label: 'D',
        heading: 'Integrations & AI',
        items: [
          { name: 'Stripe API', level: 'Primary' },
          { name: 'Google Maps SDK', level: 'Strong' },
          { name: 'Deep AR', level: 'Working' },
          { name: 'GitHub Copilot', level: 'Primary' },
          { name: 'Cursor', level: 'Primary' },
        ],
      },
    ],
    languagesLabel: 'Languages',
    languages: [
      { name: 'English', note: 'fluent' },
      { name: 'Bangla', note: 'native' },
      { name: 'German', note: 'basic' },
    ],
  },
  contact: {
    sectionNum: '05',
    sectionLabel: 'Say hello',
    headlineLine1: 'Got something',
    headlineLine2Highlight: 'interesting',
    headlineLine3: 'to build?',
    headlineLine4Italic: "Let's talk.",
    blurb:
      "I'm open to lead and senior remote roles, contract work and long-term collaborations. Fastest reply is email — I check it first thing, Dhaka time.",
    primaryEmailLabel: 'Primary · Email',
    primaryEmail: 'emailofimran1992@gmail.com',
    portfolioUrl: 'https://imran-khan-chi.vercel.app/',
    channels: [
      {
        label: 'Email',
        value: 'emailofimran1992@gmail.com',
        href: 'mailto:emailofimran1992@gmail.com',
        icon: 'mail',
      },
      {
        label: 'Phone',
        value: '+880 1340 966 449',
        href: 'tel:+8801340966449',
        icon: 'phone',
      },
      {
        label: 'LinkedIn',
        value: '/in/imran-khan-9bb7b5147',
        href: 'https://www.linkedin.com/in/imran-khan-9bb7b5147/',
        icon: 'linkedin',
      },
      {
        label: 'GitHub',
        value: '@imransid',
        href: 'https://github.com/imransid',
        icon: 'github',
      },
      {
        label: 'Based in',
        value: 'Dhaka, Bangladesh',
        href: 'https://maps.google.com/?q=Dhaka,Bangladesh',
        icon: 'map',
      },
    ],
  },
  footer: {
    firstName: 'Imran',
    lastName: 'Khan',
    copyrightName: 'Imran Khan',
    statusLabel: 'Open to work',
    builtLine: 'Built with Next · Three · Tailwind',
    githubHref: 'https://github.com/imransid',
    linkedinHref: 'https://www.linkedin.com/in/imran-khan-9bb7b5147/',
    emailHref: 'mailto:emailofimran1992@gmail.com',
  },
};
