import type { PortfolioData, SiteContent } from './types';

const marqueeSkills = [
  'React Native',
  'NestJS',
  'PostgreSQL',
  'GraphQL',
  'Stripe',
  'Docker',
  'TypeScript',
  'Redux-Saga',
  'Firebase',
  'Microservices',
];

/** Hero fields only, useful for admin defaults and tests. */
export const siteContentDefaults: SiteContent = {
  roleTagline: 'Lead Software Engineer',
  firstName: 'Imran',
  lastName: 'Khan',
  bio: '',
  location: '',
  experienceMeta: '{{years}}+ years',
  experienceFocus: 'Mobile & Backend',
};

export const defaultPortfolioData: PortfolioData = {
  version: 1,
  seo: {
    title: 'Imran Khan | Lead Engineer, Mobile & Backend',
    description:
      'Lead Software Engineer, {{years}}+ years shipping React Native apps and the NestJS backends behind them. React Native, NestJS, PostgreSQL, GraphQL. Available for remote contract work.',
    keywords: [
      'Imran Khan',
      'Lead Engineer',
      'React Native Developer',
      'NestJS',
      'Mobile Engineer',
      'Dhaka Bangladesh',
      'Portfolio',
    ],
  },
  site: {
    ...siteContentDefaults,
    bio: 'I build mobile apps and the backends behind them. React Native on the front, NestJS with PostgreSQL and GraphQL on the back. Currently Lead Engineer at Jumatechs.',
    location: 'Dhaka, Bangladesh. Available worldwide, remote.',
  },
  hero: {
    portfolioLine: 'Portfolio / 2026',
    headline: 'I build apps and the backends behind them.',
    marqueeSkills,
    ctaPrimaryLabel: 'Explore the map',
    ctaPrimaryHref: '#projects',
    ctaSecondaryLabel: 'Get in touch',
    ctaSecondaryHref: '#contact',
  },
  navigation: {
    brandMonogram: 'IK',
    brandName: 'imran khan',
    availabilityLabel: 'Available',
    timezoneCity: 'Dhaka',
    timeZone: 'Asia/Dhaka',
    navItems: [
      { label: 'About', href: '#about', num: '01' },
      { label: 'Work', href: '#experience', num: '02' },
      { label: 'Projects', href: '#projects', num: '03' },
      { label: 'Stack', href: '#skills', num: '04' },
      { label: 'Contact', href: '#contact', num: '05' },
    ],
  },
  about: {
    sectionNum: '01',
    sectionLabel: 'About',
    manifestoKicker: '',
    manifestoBody:
      "An engineer's work is half code, half judgement. I care about the judgement.",
    headlineLine1Before: 'I ship things that ',
    headlineLine1Highlight: 'work',
    headlineLine2: 'Under load, on flaky networks,',
    headlineLine3Italic: 'at 2am for a release.',
    bodyParagraphs: [
      "I've led mobile and backend work across real estate, HR, government and consumer apps. Currently Lead Engineer at Jumatechs, where I drive architecture across React Native and NestJS stacks, run CI/CD with GitHub Actions and Expo EAS, and mentor a small team of engineers.",
      'Before that I led hybrid mobile development at Intellier and shipped cross-platform products at Brain Station 23. I lean on AI tools like Copilot and Cursor to move faster without cutting corners.',
    ],
    stats: [
      { n: '{{years}}+', label: 'Years building' },
      {
        n: '{{goSmartYears}}',
        label:
          'Years since I last shipped to the Go Smart backend, still in production',
      },
      {
        n: '70,000',
        label: 'Bazzile downloads in France, in twelve months',
        source:
          'https://www.journaldelagence.com/1403035-lapplication-de-recherche-immobiliere-bazzile-veut-conquerir-la-france',
      },
      { n: '{{appsOnStores}}', label: 'Apps I worked on that are live on public stores' },
    ],
    affiliation: {
      lead: 'I also lead ',
      linkLabel: 'Bolt Fusion Tech',
      linkUrl: 'https://boltfusiontech.com',
      tail: ', a senior engineering team.',
    },
  },
  experience: {
    sectionNum: '02',
    sectionLabel: 'Selected Work History',
    titleLead: '{{years}} years of ',
    titleEmphasis: 'shipping things',
    titleTail: ' across mobile, backend and the messy bits in between.',
    roles: [
      {
        company: 'Jumatechs',
        title: 'Lead Engineer',
        period: 'Aug 2025 - Present',
        years: '2025',
        bullets: [
          'Lead a cross-functional team driving architecture and code quality across mobile and backend systems.',
          'Architect React Native apps backed by NestJS, PostgreSQL and Supabase.',
          'Built CI/CD pipelines with GitHub Actions and Expo EAS for the mobile release process.',
          'Shipped secure auth, real-time sync and Stripe payments to production.',
          'Integrated AI-assisted tooling (Copilot, Cursor) into team workflow; mentor juniors on API design, state management and testing.',
        ],
        tech: [
          'React Native',
          'NestJS',
          'PostgreSQL',
          'Supabase',
          'Expo EAS',
          'Stripe',
        ],
      },
      {
        company: 'Intellier',
        title: 'Senior Software Engineer',
        period: 'Jan 2023 - Jul 2025',
        years: '2023-25',
        bullets: [
          'Led hybrid mobile development using React Native, NestJS and Django.',
          'Architected JWT auth with row-level security policies for data integrity.',
          'Integrated Stripe payments and Google Maps SDK for location-aware features.',
          'Managed CI/CD lifecycle with GitHub Actions and Vercel.',
          'Guided technical decision-making and mentored juniors across concurrent projects.',
        ],
        tech: [
          'React Native',
          'NestJS',
          'Django',
          'Stripe',
          'Google Maps',
          'Vercel',
        ],
      },
      {
        company: 'Brain Station 23',
        title: 'Software Engineer',
        period: 'Jan 2020 - Dec 2022',
        years: '2020-22',
        bullets: [
          "Engineered secure backend services (NestJS, Django) for Modhumoti Bank's Go Smart digital banking platform, a production system still serving live customers today.",
          'Designed and shipped cross-platform applications using React Native and MSSQL.',
          'Built backend services with payment and real-time features.',
        ],
        tech: ['React Native', 'MSSQL', 'Redux', 'Agile'],
      },
    ],
  },
  projects: {
    sectionNum: '03',
    sectionLabel: 'Selected Projects',
    titleLead: "Things I've ",
    titleEmphasis: 'shipped',
    titleMid:
      ' recently. Some live in app stores, some in government, ',
    titleTailItalic: 'some on the RMG factory floor.',
    aside:
      'A selection of work across mobile, backend and the integrations that hold them together. Links go to a live app, a store listing, a demo or a case study.',
    moreSectionTitleBefore: 'More',
    moreSectionTitleEmphasis: ' work.',
    featured: [
      {
        name: 'Go Smart',
        tagline: "Modhumoti Bank's digital banking app",
        description:
          "Engineered secure backend services for Go Smart, Modhumoti Bank's digital banking platform, at Brain Station 23. A production system still serving live customers today.",
        period: '2020 - 2022',
        category: 'Digital Banking',
        tech: ['NestJS', 'Django', 'Node.js', 'REST APIs', 'PostgreSQL'],
        links: [
          {
            label: 'The Daily Star',
            url: 'https://www.thedailystar.net/business/news/brain-station-23-the-homegrown-fintech-firm-enabling-local-banks-go-digital-1952185',
          },
          {
            label: 'Google Play',
            url: 'https://play.google.com/store/apps/details?id=modhumotibankltd.com',
          },
        ],
        accent: 'from-amber-glow/30 to-transparent',
        number: '01',
        status: 'In production',
      },
      {
        name: 'WarmChats',
        tagline: 'Real estate agent CRM',
        description:
          'AI CRM for real estate agents: instant SMS, email and call response, automatic lead qualification and follow-up. Backend lead. Django CRM core, NestJS and Flask services, Telnyx voice/SMS, Claude AI for the messaging.',
        period: '',
        category: 'AI CRM',
        tech: ['Django', 'NestJS', 'Flask', 'Telnyx', 'Claude AI'],
        links: [{ label: 'warmchats.com', url: 'https://www.warmchats.com' }],
        accent: '',
        number: '09',
        status: 'Live',
      },
      {
        name: 'OPAL',
        tagline: 'Curated fashion + tech',
        description:
          'A curated fashion and tech e-commerce store I co-founded and built: catalogue, cart, secure checkout and order tracking.',
        period: '',
        category: 'E-commerce',
        tech: ['Next.js', 'Firebase', 'Firestore'],
        links: [{ label: 'opal-sooty.vercel.app', url: 'https://opal-sooty.vercel.app/' }],
        accent: '',
        number: '10',
        status: 'Live',
      },
      {
        name: 'FanLock',
        tagline: 'Creator content protection',
        description:
          'A content-protection platform for online creators that scans Telegram, Google and social media for leaked content and automates takedowns. Backend lead. Django backend, Next.js frontend.',
        period: '',
        category: 'Content Protection',
        tech: ['Next.js', 'Django'],
        links: [{ label: 'fanlock-pi.vercel.app', url: 'https://fanlock-pi.vercel.app/' }],
        accent: '',
        number: '12',
        status: 'Live',
      },
      {
        name: 'Balanzify',
        tagline: 'HR & Payroll Microservices',
        description:
          'An HR and payroll platform built as NestJS microservices: onboarding, payslips, attendance, tax logic and leave management, all speaking GraphQL.',
        period: 'Jul 2025 - Ongoing',
        category: 'HR & Payroll SaaS',
        tech: ['NestJS', 'PostgreSQL', 'GraphQL', 'Microservices'],
        links: [{ label: 'balanzify.com', url: 'https://balanzify.com' }],
        accent: 'from-amber-glow/30 to-transparent',
        number: '02',
        status: 'In production',
      },
      {
        name: 'Go Style Business',
        tagline: 'Salon business management',
        description:
          'A salon business management platform, in production serving real salons. Backend lead. Multi-tenant NestJS and Prisma backend on PostgreSQL, deployed on Docker Swarm.',
        period: '',
        category: 'Salon SaaS',
        tech: ['NestJS', 'Prisma', 'PostgreSQL', 'Docker Swarm'],
        links: [{ label: 'business.gostyle.uk', url: 'https://business.gostyle.uk/' }],
        accent: '',
        number: '11',
        status: 'In production',
      },
      {
        name: 'Bazzile',
        tagline: 'Real Estate Marketplace',
        description:
          'The app has passed 70,000 downloads in France in twelve months, with around 15,000 active users there. I shipped features into the Bazzile React Native app: swipe-based browsing, Google Maps location matching and Firebase real-time sync. Bazzile is a Swiss real estate marketplace based in Geneva, where listings come only from professional agencies, are ranked by an AI matching model, and sync with most agency CRMs. Live on the App Store and Google Play.',
        period: 'Jan 2025 - Jul 2025',
        category: 'Consumer Mobile',
        tech: [
          'React Native',
          'Firebase',
          'Redux-Saga',
          'Reanimated',
          'NestJS',
        ],
        links: [
          {
            label: 'App Store',
            url: 'https://apps.apple.com/fr/app/bazzile/id1622224603',
          },
          {
            label: 'Google Play',
            url: 'https://play.google.com/store/apps/details?id=com.bazzile.app',
          },
          {
            label: 'Journal de l\'Agence',
            url: 'https://www.journaldelagence.com/1403035-lapplication-de-recherche-immobiliere-bazzile-veut-conquerir-la-france',
          },
        ],
        accent: 'from-amber-glow/25 to-transparent',
        number: '03',
        status: 'Live',
      },
      {
        name: 'Bangladesh RAB',
        tagline: 'Government CMS',
        description:
          'Led the backend architecture for the Bangladesh Rapid Action Battalion content management system: microservices in TypeScript and NestJS, the APIs behind them, and a Next.js frontend. Deployed at rab.gov.bd.',
        period: 'Jan 2024 - Dec 2024',
        category: 'Government',
        tech: ['NestJS', 'TypeScript', 'PostgreSQL', 'Docker', 'Next.js'],
        links: [{ label: 'www.rab.gov.bd', url: 'https://www.rab.gov.bd' }],
        accent: 'from-amber-glow/20 to-transparent',
        number: '04',
        status: 'Live',
      },
      {
        name: 'Myrep',
        tagline: 'Field Rep Companion',
        description:
          'Shipped features for Myrep, a Jumatechs field-rep app: customer support, task tracking and real-time rep communication, with in-app chat, push notifications and WatermelonDB offline sync so it keeps working on flaky networks.',
        period: 'Jan 2025 - Sep 2025',
        category: 'B2B Mobile',
        tech: ['React Native', 'WatermelonDB', 'NestJS', 'GraphQL', 'Sentry'],
        links: [
          {
            label: 'Google Play',
            url: 'https://play.google.com/store/apps/details?id=com.myref.app',
          },
        ],
        accent: 'from-bone/10 to-transparent',
        number: '05',
        status: 'Live',
      },
      {
        // TODO(imran): the deployed demo's page title is "Playerzone", this card says "Playzone".
        // Owner is fixing the deployed app. Do NOT ship until the name matches the live title.
        name: 'Playzone',
        tagline: 'Real-time multiplayer, classic games, no signups',
        description:
          'A real-time multiplayer platform for classic games with friends, no signups required. NestJS microservices handle game logic and matchmaking, PostgreSQL stores state, and Socket.IO syncs players in under a second. Next.js frontend, containerized with Docker.',
        period: '2024 - Present',
        category: 'Full-Stack, Real-Time Web App',
        tech: [
          'Next.js',
          'TypeScript',
          'NestJS',
          'Socket.IO',
          'PostgreSQL',
          'Docker',
          'Microservices',
          'Tailwind CSS',
        ],
        links: [{ label: 'Demo', url: 'https://playzone-update.vercel.app/' }],
        accent: 'from-amber-glow/30 to-transparent',
        number: '06',
        status: 'Live',
      },
    ],
    more: [
      {
        name: 'GodConnect Online',
        tagline: 'Community app with live broadcasts',
        description:
          'Shipped features for GodConnect Online, a community app with groups, live broadcasts, messaging, media uploads and a GPS-based church finder. Live on both stores.',
        period: '2023 - 2024',
        category: 'Social',
        tech: ['React Native', 'Redux-Saga', 'WatermelonDB', 'Firebase'],
        links: [
          {
            label: 'App Store',
            url: 'https://apps.apple.com/us/app/godconnect-online/id1518393186',
          },
          {
            label: 'Google Play',
            url: 'https://play.google.com/store/apps/details?id=com.godconnect.online',
          },
        ],
        accent: '',
        number: '07',
        status: 'Live',
      },
      {
        name: 'NIdle Finishing',
        tagline: 'RMG sector digitalization',
        description:
          'Digitized the finishing stage for a ready-made-garments factory floor. React Native app over GraphQL and NestJS.',
        period: 'Nov 2023 - Feb 2024',
        category: 'Industrial',
        tech: ['React Native', 'GraphQL', 'NestJS'],
        links: [{ label: 'Case study', url: 'https://intellier.com/nidle/' }],
        accent: '',
        number: '08',
        status: '',
      },
      {
        name: 'IQ Test',
        tagline: 'Android consumer app',
        description:
          'Built IQ Test, a Jumatechs app live on Google Play: a React Native front end with a Django and PostgreSQL backend and Firebase push notifications.',
        period: '',
        category: 'Consumer Mobile',
        tech: ['React Native', 'Redux', 'Reanimated', 'Firebase', 'Django', 'PostgreSQL'],
        links: [
          {
            label: 'Google Play',
            url: 'https://play.google.com/store/apps/details?id=com.iqapp.test',
          },
        ],
        accent: '',
        number: '13',
        status: 'Live',
      },
      {
        name: 'Cleva',
        tagline: 'Bill-payment wallet',
        description:
          'Built Cleva, a Jumatechs app live on Google Play: a wallet for adding a card and paying bills, on a React Native front end with a Django and PostgreSQL backend.',
        period: '',
        category: 'Fintech Mobile',
        tech: ['React Native', 'Redux', 'Reanimated', 'Firebase', 'Django', 'PostgreSQL'],
        links: [
          {
            label: 'Google Play',
            url: 'https://play.google.com/store/apps/details?id=com.cleva.paybill',
          },
        ],
        accent: '',
        number: '14',
        status: 'Live',
      },
    ],
    archiveLine:
      'Also shipped: Team Pharma (NestJS microservices, 2024), JTI Sheikh (Deep AR, 2021).',
  },
  skills: {
    sectionNum: '04',
    sectionLabel: 'Toolbox',
    titleLead: 'The ',
    titleEmphasis: 'tools',
    titleTail: ' I reach for, grouped by where they live in the stack.',
    legendPrimary: 'Primary, daily',
    legendStrong: 'Strong, in production',
    legendWorking: 'Working, shipped with',
    groups: [
      {
        label: 'A',
        heading: 'Mobile',
        items: [
          { name: 'React Native', level: 'Primary' },
          { name: 'Expo EAS', level: 'Primary' },
          { name: 'Redux / Redux-Saga', level: 'Primary' },
          { name: 'React Reanimated', level: 'Strong' },
          { name: 'WatermelonDB', level: 'Strong' },
          { name: 'iOS / App Store', level: 'Strong' },
          { name: 'Android / Play Store', level: 'Strong' },
          { name: 'Push Notifications', level: 'Strong' },
        ],
      },
      {
        label: 'B',
        heading: 'Backend',
        items: [
          { name: 'NestJS', level: 'Primary' },
          { name: 'TypeScript', level: 'Primary' },
          { name: 'GraphQL', level: 'Primary' },
          { name: 'PostgreSQL', level: 'Primary' },
          { name: 'Django', level: 'Strong' },
          { name: 'Supabase', level: 'Strong' },
          { name: 'Firebase', level: 'Strong' },
          { name: 'Microservices', level: 'Strong' },
          { name: 'JWT Auth / RLS', level: 'Strong' },
          { name: 'MSSQL', level: 'Working' },
        ],
      },
      {
        label: 'C',
        heading: 'Infra & DevEx',
        items: [
          { name: 'Docker', level: 'Strong' },
          { name: 'GitHub Actions', level: 'Primary' },
          { name: 'Vercel', level: 'Strong' },
          { name: 'Sentry', level: 'Strong' },
          { name: 'Unit Testing', level: 'Strong' },
          { name: 'Husky / pre-commit', level: 'Working' },
        ],
      },
      {
        label: 'D',
        heading: 'Integrations & AI',
        items: [
          { name: 'Stripe API', level: 'Primary' },
          { name: 'Google Maps SDK', level: 'Strong' },
          { name: 'Deep AR', level: 'Working' },
          { name: 'GitHub Copilot', level: 'Primary' },
          { name: 'Cursor', level: 'Primary' },
        ],
      },
    ],
    languagesLabel: 'Languages',
    languages: [
      { name: 'English', note: 'fluent' },
      { name: 'Bangla', note: 'native' },
      { name: 'German', note: '' },
    ],
  },
  contact: {
    sectionNum: '05',
    sectionLabel: 'Say hello',
    headlineLine1: 'Got something',
    headlineLine2Highlight: 'interesting',
    headlineLine3: 'to build?',
    headlineLine4Italic: "Let's talk.",
    blurb:
      "I'm open to lead and senior remote roles, contract work and long-term collaborations. Email is the fastest way to reach me; I check it first thing, Dhaka time.",
    primaryEmailLabel: 'Primary, Email',
    primaryEmail: 'emailofimran1992@gmail.com',
    portfolioUrl: 'https://imran-khan-chi.vercel.app/',
    channels: [
      {
        label: 'Email',
        value: 'emailofimran1992@gmail.com',
        href: 'mailto:emailofimran1992@gmail.com',
        icon: 'mail',
      },
      {
        label: 'Phone',
        value: '+880 1340 966 449',
        href: 'tel:+8801340966449',
        icon: 'phone',
      },
      {
        label: 'LinkedIn',
        value: '/in/imran-khan-9bb7b5147',
        href: 'https://www.linkedin.com/in/imran-khan-9bb7b5147/',
        icon: 'linkedin',
      },
      {
        label: 'GitHub',
        value: '@imransid',
        href: 'https://github.com/imransid',
        icon: 'github',
      },
      {
        label: 'Based in',
        value: 'Dhaka, Bangladesh',
        href: 'https://maps.google.com/?q=Dhaka,Bangladesh',
        icon: 'map',
      },
    ],
  },
  footer: {
    firstName: 'Imran',
    lastName: 'Khan',
    copyrightName: 'Imran Khan',
    statusLabel: 'Open to work',
    builtLine: 'Built with Next and Tailwind',
    githubHref: 'https://github.com/imransid',
    linkedinHref: 'https://www.linkedin.com/in/imran-khan-9bb7b5147/',
    emailHref: 'mailto:emailofimran1992@gmail.com',
  },
};
